server:
  port: 8083

spring:
  application:
    name: access-service
  datasource:
    url: jdbc:postgresql://${ACCESS_DB_HOST:localhost}:${ACCESS_DB_PORT:5435}/${ACCESS_DB_NAME:access}
    username: ${ACCESS_DB_USER:access}
    password: ${ACCESS_DB_PASSWORD:access}
    driver-class-name: org.postgresql.Driver

bnb:
  smartlock:
    # Default to stub so local/dev environments don't fail without credentials.
    # Set to "routing" to enable Yale/Seam routing.
    mode: stub
    yale:
      enabled: false
      # Example: https://api.yale.example
      base-url: ${YALE_BASE_URL:}
      # Bearer token used to call the Yale API (format depends on your Yale integration).
      access-token: ${YALE_ACCESS_TOKEN:}
      # Path templates; variables: {deviceId}, {grantId}
      grant-path: /locks/{deviceId}/access-grants
      revoke-path: /locks/{deviceId}/access-grants/{grantId}/revoke
    seam:
      enabled: false
      base-url: https://connect.getseam.com
      api-key: ${SEAM_API_KEY:}
      create-access-code-path: /access_codes/create
      delete-access-code-path: /access_codes/delete

management:
  endpoints:
    web:
      exposure:
        include: health,info
