server:
  port: 8081

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://${BOOKING_DB_HOST:localhost}:${BOOKING_DB_PORT:5433}/${BOOKING_DB_NAME:booking}
    username: ${BOOKING_DB_USER:booking}
    password: ${BOOKING_DB_PASSWORD:booking}
    hikari:
      maximum-pool-size: ${BOOKING_DB_POOL_SIZE:10}
      minimum-idle: ${BOOKING_DB_MIN_IDLE:2}
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
